### ISSUE TITLE
Error HH404

### ISSUE THREAD

**Issue by enzofoucaud** [mikoim/sunflower-farmers-bot#1]
Hello,

I try to launch bot.

However I have this message in Windows, WSL and Linux.

npm version = 17.X
and I follow all command line in README

Error HH404: File ../openzeppelin-contracts-v3.3.0/contracts/token/ERC721/ERC721.sol, imported from contracts/Armour.sol, not found.

**Comment by mikoim** [comment]
```shell
git submodule update --init --recursive
```

**Comment by enzofoucaud** [comment]
Thanks for your help, but don't work ^^

![image](https://user-images.githubusercontent.com/15039645/147912383-97300ece-0a74-47ca-8c76-0e8779b851fb.png)
