### ISSUE TITLE
How run the env command?

### ISSUE THREAD

**Issue by lucasreinaldi** [mikoim/sunflower-farmers-bot#5]
I'm getting this error when I try to run the readme command: 
![image](https://user-images.githubusercontent.com/22507013/148060117-1b8b35ae-fd4a-46be-b905-dfcb065d4177.png)

Can you explain more how can I use multi acc?

**Comment by lucasreinaldi** [comment]
Meh, I just solved. 
I meant to use bash, and was using command prompt.

**Comment by Green37182** [comment]
conseguiu passar a taxa de gas dps?

**Comment by lucasreinaldi** [comment]
> 

Ta dando ruim aqui também :/
